---
title: "Untitled"
output: pdf_document
date: "2024-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(skimr)
```

```{r}
df <- read.csv("../../data/gapminder-data.csv")
```

```{r}
df_sub <- read_csv("../../data/gapminder-data.csv",
  col_select=c("Country", "Year", "gdp_per_capita"),
  na=c("", "NA"))
```

```{r}
head(df)
```

```{r}
tail(df)
```

```{r}
spec(df)
```

```{r}
glimpse(df)
```

```{r}
summary(df)
```

```{r}
skim(df)
```

```{r}
data(iris)
df_iris <- group_by(iris, Species)
df_iris <- summarize_if(df_iris, is.numeric, mean)
```

```{r}
data(iris)
df_iris <- iris %>%
  group_by(Species) %>%
  summarize_if(is.numeric, mean)
```

```{r get_data}
header <- c("age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex", "capital_gain",
  "capital_loss", "hours_per_week", "native_country", "target")
df <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
  col_names=header, trim_ws=TRUE)
```

```{r}
df %>% slice_head(n=5)
```

```{r}
df %>% slice_tail(n=5)
```

```{r}
df %>% slice_min(age, prop=0.10)
```

```{r}
df %>% slice_max(age, prop=0.30)
```

```{r}
df %>% slice_sample(n=10, replace=TRUE)
```

```{r}
df %>% filter(age > 30)
```

```{r}
df %>% select(marital_status, age)
```

```{r}
df %>% distinct(sex)
```

```{r}
df %>% group_by(workclass) %>%
  summarize(age_avg=mean(age))
```

```{r}
df %>% group_by(workclass) %>% summarize(n())
```

```{r}
df %>% summarize(sum(!is.na(workclass)))
```

```{r}
df %>% group_by(workclass) %>% summarize(first(age))
```

```{r}
df %>% group_by(workclass) %>% summarize(sd(capital_gain))
```

```{r}
df %>% group_by(workclass) %>% summarize(quantile(age, 0.5))
```

```{r}
df %>% select(1, 3, 5, 11, 12, 13) %>% summarize(across(everything(), mean))
```

```{r}
df %>% arrange(native_country)
```

```{r}
df %>%
  group_by(education) %>%
  summarize(count=n(),
            avg_net_gain=mean(capital_gain - capital_loss)) %>%
  arrange(desc(avg_net_gain))
```

```{r}
df %>% separate(target, into=c("sign", "amount"), sep="\\b")
```

```{r}
df %>% unite(sex, race, age, col="description", sep="_", remove=FALSE)
```

```{r}
df %>% mutate(total_gain=capital_gain - capital_loss,
              tax=ifelse(total_gain >= 15000,
                         total_gain * 0.1,
                         0)
) %>%
  arrange(desc(tax))
```

```{r}
for (variable in colnames(df)){
  print(
    paste(variable, dim(drop_na(df[df[variable]=="?", variable]))[1])
  )
}
```

```{r}
df_replaced <- df %>%
  mutate(workclass=replace(workclass, workclass=="?", NA),
  occupation=replace(occupation, occupation=="?", NA),
  native_country=replace(native_country, native_country=="?", NA)
  )
```

```{r}
for (variable in colnames(df_replaced)){
  print(
    paste(variable, dim(drop_na(df_replaced[df_replaced[variable]=="?", variable]))[1])
  )
}
```

```{r}
df %>%
  mutate(over_under=recode(target, "<=50K"="under",
                           ">50K"="over")) %>%
  select(target, over_under)
```

```{r}
df %>%
  mutate(age_avg=mean(age),
         over_under_age_avg=cut(age,
              c(0, mean(age), max(age)),
              c("Lower than avg", "Above the avg"))
  ) %>%
  select(age, age_avg, over_under_age_avg)
```

```{r data}
sales <- data.frame(
  date = c("2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04", "2022-01-05"),
  store_cd= c(1, 2, 3, 4, 5),
  product_cd= c(1, 2, 3, 4, 5),
  qty= c(10, 12, 9, 12, 8), 
  sales= c(30, 60, 45, 24, 32)
)

stores <- data.frame(
  store_cd= c(1, 2, 3, 4, 6),
  address= c("1 main st", "20 side st", "19 square blvd", "101 first st", "1002 retail ave"),
  city= c("Main", "East", "West", "North", "South"), 
  open_hours= c("7-23", "7-23", "9-21", "9-21", "9-21")
  )

products <- data.frame(
  product_cd= c(1, 2, 3, 4, 6),
  description= c("Soft drink", "Frozen snack", "Fruit", "Water", "Fruit 2"),
  unit_price= c(3.0, 5.0, 5.0, 2.0, 4.0), 
  unit_measure= c("each", "each", "kg", "each", "kg")
  )
```



