---
title: "Flexdashboard 2" # Your title
runtime: shiny # This time, we need shiny to incorporate shiny elements like widgets
output: 
  flexdashboard::flex_dashboard:
    orientation: rows # We change the orientation of the dashboard elements
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Load the libraries - We need the flexdashboard package
library(flexdashboard)
library(tidyverse)
library(leaflet)

# Load the data set
load("geocodedData.Rdata")
```

<!-- Create a sidebar on the left part of the dashboard -->

Column {.sidebar}
-----------------------------------------------------------------------

<!-- This is the title of the side bar -->

### Widgets

<!-- R code to create what will be displayed in the column.
     We can now include Shiny widgets. -->

```{r}
# Make a slider to select the years
sliderInput("year",
            "Years included",
            min = 1952,
            max = 2007,
            value = c(1952, 2007),
            sep = "",
            step = 5
)

# Make a check box to display the trend
checkboxInput("linear", label = "Add trend line?", value = FALSE)
```

<!-- On the right part of the dashboard, the rows will be displayed
     on top of each other. -->

Row
-----------------------------------------------------------------------

<!-- This is the title of the row -->

### Life expectancy over time

<!-- R code to create what will be displayed in the column.
     We can now include Shiny interactive elements and
     use the input from the widgets. -->

```{r}
renderPlot({
  
  thePlot = mapData %>%
    # Select the years displayed with the slider
    filter(year >= input$year[1], year <= input$year[2]) %>%
    group_by(continent, year) %>%
    summarise(meanLife = mean(lifeExp)) %>%
    ggplot(aes(x = year, y = meanLife, group = continent, colour = continent)) +
    geom_line()

  # Show the trend if the box is checked by the user
  if(input$linear){ 
    thePlot = thePlot + geom_smooth(method = "lm") 
  } 
  
  print(thePlot)
})
```

<!-- We can have several tabs on the row. -->

Row {.tabset}
-----------------------------------------------------------------------

<!-- This is the title of the first tab -->

### Life expectancy

<!-- R code to create what will be displayed in the column.
     We can now include Shiny interactive elements and
     use the input from the widgets. -->

```{r}

renderLeaflet({
  
  mapData %>%
    filter(year == input$year[2]) %>%
    leaflet() %>%
    addTiles() %>%
    setView(lng = 0, lat = 0, zoom = 2) %>%
    addCircles(lng = ~ lon, lat = ~ lat, weight = 1,
               radius = ~ lifeExp * 5000, 
               popup = ~ paste(country, lifeExp))
})

```

<!-- This is the title of the second tab -->

### GDP per capita

<!-- R code to create what will be displayed in the column.
     We can now include Shiny interactive elements and
     use the input from the widgets. -->

```{r}

renderLeaflet({
  
  mapData %>%
    filter(year == input$year[2]) %>%
    leaflet() %>%
    addTiles() %>%
    setView(lng = 0, lat = 0, zoom = 2) %>%
    addCircles(lng = ~ lon, lat = ~ lat, weight = 1,
               radius = ~ log(gdpPercap) * 25000, 
               popup = ~ paste(country, gdpPercap))
})

```
