---
title: "STAT 451 - Visualizing Data - Autumn 2025" # Your title
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Load the libraries - We need the flexdashboard package
library(flexdashboard)
library(tidyverse)
library(leaflet)

# Load the data set
load("geocodedData.Rdata")
```

<!-- Create a first column on the left part of the dashboard -->

Column {data-width=650}
-----------------------------------------------------------------------

<!-- This is the title of the column -->

### Life expectancy over time

<!-- R code to create what will be displayed in the column -->

```{r}

# We just make a line plot of the data with ggplot2

mapData %>%
  group_by(continent, year) %>%
  summarise(meanLife = mean(lifeExp)) %>%
  ggplot(aes(x = year, y = meanLife, group = continent, colour = continent)) +
  geom_line()

```

<!-- Create a second column on the right of the first column -->

Column {data-width=350}
-----------------------------------------------------------------------

<!-- We can have several rows: each one has a title and a content defined by
     the R Markdown header and the R code block -->

<!-- This is the title of the first row -->

### Life expectancy

<!-- R code to create what will be displayed in the row -->

```{r}

# Now we are plotting a map

mapData %>%
  filter(year == 2007) %>%
  leaflet() %>%
  addTiles() %>%
  setView(lng = 0, lat = 0, zoom = 2) %>%
  addCircles(lng = ~ lon, lat = ~ lat, weight = 1,
             radius = ~ lifeExp * 5000, 
             popup = ~ paste(country, lifeExp))

```

<!-- This is the title of the second row -->

### GDP per capita

<!-- R code to create what will be displayed in the row -->

```{r}

# Now we are plotting another map

mapData %>%
  filter(year == 2007) %>%
  leaflet() %>%
  addTiles() %>%
  setView(lng = 0, lat = 0, zoom = 2) %>%
  addCircles(lng = ~ lon, lat = ~ lat, weight = 1,
             radius = ~ log(gdpPercap) * 25000, 
             popup = ~ paste(country, gdpPercap))

```
