---
title: "Untitled"
output: pdf_document
date: "2023-10-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(mice)
```

```{r data_join}
sales <- data.frame(
  date = c("2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04", "2022-01-05"),
  store_cd= c(1, 2, 3, 4, 5),
  product_cd= c(1, 2, 3, 4, 5),
  qty= c(10, 12, 9, 12, 8), 
  sales= c(30, 60, 45, 24, 32)
)

stores <- data.frame(
  store_cd= c(1, 2, 3, 4, 6),
  address= c("1 main st", "20 side st", "19 square blvd", "101 first st", "1002 retail ave"),
  city= c("Main", "East", "West", "North", "South"), 
  open_hours= c("7-23", "7-23", "9-21", "9-21", "9-21")
  )

products <- data.frame(
  product_cd= c(1, 2, 3, 4, 6),
  description= c("Soft drink", "Frozen snack", "Fruit", "Water", "Fruit 2"),
  unit_price= c(3.0, 5.0, 5.0, 2.0, 4.0), 
  unit_measure= c("each", "each", "kg", "each", "kg")
  )
```

```{r left_join}
sales %>% left_join(products, by="product_cd")
```

```{r right_join}
sales %>% right_join(stores, by="store_cd")
```
```{r inner_join}
sales %>% inner_join(stores, by="store_cd")
```

```{r full_join}
sales %>% full_join(stores)
```

```{r anti_join}
sales %>% anti_join(products)
```

```{r data2}
df_wide <- data.frame(
  project = c("project1", "project2", "project3"),
  Jan= sample(1000:2000, 3),
  Feb= sample(1000:2000, 3),
  Mar= sample(1000:2000, 3)
)
```

```{r long}
df_long <- df_wide %>%
  pivot_longer(cols=2:4,
               names_to = "months",
               values_to = "expenses")
```

```{r wide}
df_wide_2 <- df_long %>%
  pivot_wider(names_from = "months",
              values_from = "expenses")
```

## Missing data

```{r get_data}
header <- c("age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex", "capital_gain",
  "capital_loss", "hours_per_week", "native_country", "target")
df <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
  col_names=header, trim_ws=TRUE)
df <-df %>%
  mutate(workclass = na_if(workclass, "?"),
         occupation = na_if(occupation, "?"),
         native_country = na_if(native_country, "?"))
```
```{r fill}
df_fill1 <- df %>%
  fill(workclass, occupation, native_country, .direction="down")
```

```{r freq}
m_freq_workcls <- names(table(df$workclass))[which.max(table(df$workclass))]
m_freq_occup <- names(table(df$occupation))[which.max(table(df$occupation))]
df_fill2 <- df %>%
  replace_na(list(workclass = m_freq_workcls,
                  occupation = m_freq_occup))
```

```{r na_omit}
df_no_na <- df %>% na.omit()
```

```{r drop_na}
df_native <- df %>%
  drop_na(native_country)
```

```{r data}
data("txhousing")
txhousing$date <- date_decimal(txhousing$date, tz="GMT")
txhousing$city <- as.factor(txhousing$city)
```

```{r drop_5nas}
idx <- which(rowSums(is.na(txhousing)) == 5)
txhousing <- txhousing[-idx,]
```

```{r impute_median}
txhousing$sales[is.na(txhousing$sales)] <- median(txhousing$sales, na.rm=TRUE)
txhousing$volume[is.na(txhousing$volume)] <- median(txhousing$volume, na.rm=TRUE)
txhousing$median[is.na(txhousing$median)] <- median(txhousing$median, na.rm=TRUE)
```

```{r impute_mice}
impute <- mice(data.frame(txhousing[,7:8]), seed=123)
```

```{r impue_mice_2}
impute_data <- complete(impute, 1)
txhousing_clean <- txhousing %>%
  mutate(listings = impute_data[,1],
         inventory = impute_data[,2])
```

```{r data_missing}
stocks <- tibble(
  year  = c(2020, 2020, 2020, 2020, 2021, 2021, 2021),
  qtr   = c(   1,    2,    3,    4,    2,    3,    4),
  price = c(1.88, 0.59, 0.35,   NA, 0.92, 0.17, 2.66)
)
```

```{r wider_stocks}
stocks %>%
  pivot_wider(names_from = qtr,
              values_from = price)
```

```{r complete}
stocks %>% complete(year, qtr)
```

```{r load_rvest}
library(rvest)
```

```{r read_page}
page <- "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
gdp <- rvest::read_html(page)
```

```{r read_gdp}
gdp_df <- gdp %>%
  html_elements(xpath='//*[@id="mw-content-text"]/div[1]/table[2]') %>%
  html_table()
```

```{r load_json}
library(httr)
library(jsonlite)
```

```{r url}
url <- "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/mts/mts_table_1"
treasury_api <- GET(url)
```

```{r read_json}
result <- content(treasury_api, "text", encoding="UTF-8")
df_json <- fromJSON(result, flatten=TRUE)
df <- as.data.frame(df_json$data)
```

```{r map}
mtcars %>% select(hp, wt) %>% map(mean)
```

```{r rbind}
A <- mtcars[1:3,]
B <- mtcars[4:6,]
AB <- A %>% bind_rows(B)
```

```{r cbind}
A <- mtcars[1:5, 1:3]
B <- mtcars[1:5, 4:6]
AB <- A %>% bind_cols(B)
```

```{r case_when}
mtcars %>%
  mutate(transmission_type =
    case_when(
      am == 0 ~ "automatic",
      am == 1 ~ "manual"))
```

    ))
