---
title: "Ggplot2 tutorial - Command lines"
author: "Ariane Ducellier"
date: "7/18/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(ggplot2)
library(gridExtra)
library(Lock5Data)
```

# Part 1 - Basic plotting in ggplot2

## Histograms

```{r block1}
hist(airquality$Temp)
```

```{r block2}
qplot(airquality$Temp)
```

```{r block3}
ggplot(airquality, aes(x=Temp)) + geom_histogram()
```

## Bar plots

```{r block4}
df_desc <- read.csv("../data/historical-hourly-weather-data/weather_description.csv")
ggplot(df_desc, aes(x=Vancouver)) + geom_bar()
```

```{r block5}
ggplot(RetailSales, aes(x=Month, y=Sales)) + geom_bar(stat="identity")
```

## Box plots

```{r block6}
df_hum <- read.csv("../data/historical-hourly-weather-data/humidity.csv")
df_hum$datetime <- as.character(df_hum$datetime)
df_hum$month <- substr(df_hum$datetime, 6, 7)
ggplot(df_hum, aes(x=month, y=Vancouver)) + geom_boxplot()
```

## Scatter plots and line plots

```{r block7}
a = 3.4
v0 = 27
time <- runif(50, min=0, max=200)
distance <- sapply(time, function(x) v0 * x + 0.5 * a * x^2)
df <- data.frame(time,distance)
ggplot(df, aes(x=time, y=distance)) + geom_point()
ggplot(df, aes(x=time, y=distance)) + geom_line()
```

## Changing histogram defaults and adding aesthetics

```{r block8}
df_hum <- read.csv("../data/historical-hourly-weather-data/humidity.csv")
ggplot(df_hum, aes(x=Vancouver)) + geom_histogram()
ggplot(df_hum, aes(x=Vancouver)) + geom_histogram(bins=15)
ggplot(df_hum, aes(x=Vancouver)) + geom_histogram(bins=15, fill="white", color=1)
ggplot(df_hum, aes(x=Vancouver)) +
geom_histogram(bins=15, fill="white", color=1) +
ggtitle("Humidity for Vancouver city") +
xlab("Humidity") +
theme(axis.text.x=element_text(size=12), axis.text.y=element_text(size=12))
```

## Changing boxplot defaults and adding aesthetics

```{r block9}
df_hum <- read.csv("../data/historical-hourly-weather-data/humidity.csv")
df_hum$datetime <- as.character(df_hum$datetime)
df_hum$month <- substr(df_hum$datetime, 6, 7)
ggplot(df_hum, aes(x=month, y=Vancouver)) + 
geom_boxplot(color=1, fill=3) + 
ylab("Humidity") + 
theme(axis.text.x=element_text(size=15),
axis.text.y=element_text(size=15),
axis.title.x=element_text(size=15, color=2),
axis.title.y=element_text(size=15, color=2))
```

# Part 2 - Grammar of graphics and visual components

## Layers

```{r block10}
df <- read.csv("../data/gapminder-data.csv")
p1 <- ggplot(df, aes(x=Electricity_consumption_per_capita))
p2 <- p1 + geom_histogram()
p3 <- p1 + geom_histogram(bins=15)
p4 <- p3 + xlab("Electricity consumption per capita")
p2
p3
p4
```

## Scales

```{r block11}
p1 <- ggplot(df, aes(x=gdp_per_capita))
p2 <- p1 + geom_histogram()
p3 <- p2 + scale_x_continuous(name='GDP per capita ($)',
                              limits=c(0, 50000),
                              breaks=seq(0, 40000, 4000),
                              labels=c('0', '4K', '8K', '12K', '16K', '20K',
                                       '24K', '28K', '32K', '36K', '40K'))
p3
```

## Polar coordinates

```{r block12}
t <- seq(0, 360, by=15)
r <- 2
qplot(r, t) + 
coord_polar(theta="y") +
scale_y_continuous(breaks=seq(0, 360, 30))
```

## Facets

```{r block13}
p <- ggplot(df, aes(x=gdp_per_capita, y=Electricity_consumption_per_capita)) + geom_point()
p + facet_grid(Country ~ .)
p + facet_grid(. ~ Country)
p + facet_wrap(~Country)
```

## Shapes and colors

```{r block14}
dfs <- subset(df, Country %in% c("Germany", "India", "China", "United States"))
var1 <- "Electricity_consumption_per_capita"
var2 <- "gdp_per_capita"
name1 <- "Electricity/capita"
name2 <- "GDP/capita"
p1 <- ggplot(df, aes_string(x=var1, y=var2)) +
geom_point(color=2, shape=2) + 
xlim(0, 10000) + xlab(name1) + ylab(name2)
p2 <- ggplot(dfs, aes_string(x=var1, y=var2)) +
geom_point(aes(color=Country, shape=Country)) +
xlim(0, 10000) + xlab(name1) + ylab(name2)
grid.arrange(p1, p2, nrow = 2)
```

## Themes

```{r block15}
dfn <- subset(HollywoodMovies,
              Genre %in% c("Action", "Adventure", "Comedy", "Drama",
              "Romantic Comedy") &
              LeadStudio %in% c("Lionsgate ", "Paramount Pictures ",
              "Twentieth Century Fox ", "Universal Pictures ", "Warner Bros. "))
p1 <- ggplot(dfn, aes(x=Genre, y=WorldGross)) 
p2 <- p1 + geom_bar(aes(fill=LeadStudio), stat="Identity", position="dodge")
p3 <- p2 + theme(axis.title.x=element_text(size=15),
                 axis.title.y=element_text(size=15),
                 plot.background=element_rect(fill="gray87"),
                 panel.background=element_rect(fill="beige"),
                 panel.grid.major=element_line(color="Gray", linetype=1))
p3
```

```{r block16}
p4 <- p2 + theme_bw() + ggtitle("theme_bw()")
p5 <- p2 + theme_classic() + ggtitle("theme_classic()")
p6 <- p2 + theme_classic() + ggtitle("theme_gray()")
p7 <- p2 + theme_minimal() + ggtitle("theme_minimal()")
grid.arrange(p4, p5, p6, p7, nrow=2, ncol=2)
```

```{r block17}
mytheme <- theme(legend.title=element_blank(),
legend.position="bottom",
text = element_text(color="Blue"),
axis.text=element_text(size=12, color="Red"),
axis.title=element_text(size=rel(1.5)))
p2 <- p2 + ggtitle("Original Plot")
p8 <- p2 + mytheme + ggtitle("Changed Plot with my theme")
grid.arrange(p2, p8, ncol=2)
```

```{r block18}
p4 + scale_fill_brewer(palette="Spectral")
p4 + scale_fill_brewer(palette="Pastel1")
p4 + scale_fill_brewer(palette="Oranges")
```
