---
title: "Tidyverse tutorial 2 - More advanced operations"
author: "Ariane Ducellier"
date: "10/05/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load R packages.

```{r libraries}
library(tidyverse)
```

# 1. Dealing with missing data

```{r get_data}
header <- c("age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex", "capital_gain",
  "capital_loss", "hours_per_week", "native_country", "target")
df <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
  col_names=header, trim_ws=TRUE)
df <-df %>%
  mutate(workclass = na_if(workclass, "?"),
         occupation = na_if(occupation, "?"),
         native_country = na_if(native_country, "?"))
```

## 1.1 Filling values with previous value

```{r fill_previous}
df_fill1 <- df %>%
  fill(workclass, occupation, native_country, .direction="down")
```

## 1.2 Filling values with most frequent value

For categorical variables.

```{r fill_frequent}
m_freq_workcls <- names(table(df$workclass))[which.max(table(df$workclass))]
m_freq_occup <- names(table(df$occupation))[which.max(table(df$occupation))]
df_fill2 <- df %>%
  replace_na(list(workclass = m_freq_workcls,
                  occupation = m_freq_occup))
```

## 1.3 Dropping rows with missing values

```{r drop}
df_no_na <- df %>%
  drop_na()
```
