---
title: "Ggplot2 tutorial - Command lines Part 2"
author: "Ariane Ducellier"
date: "10/12/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load R packages

```{r libraries}
library(tidyverse)
library(ggpubr)
library(gridExtra)
library(Lock5Data)
```

# Part 2 - Grammar of Graphics and Visual Components

## Layers

```{r block10}
df <- read_csv("../data/gapminder-data.csv")
p1 <- ggplot(df, aes(x=Electricity_consumption_per_capita))
p2 <- p1 + geom_histogram()
p2
```

```{r block11}
p3 <- p1 + geom_histogram(bins=15)
p3
```

```{r block12}
p4 <- p3 + xlab("Electricity consumption per capita")
p4
```

## Scales

```{r block13}
df <- read_csv("../data/gapminder-data.csv")
p1 <- ggplot(df, aes(x=gdp_per_capita))
p2 <- p1 + geom_histogram()
p3 <- p2 + scale_x_continuous(name='GDP per capita ($)',
                              limits=c(0, 50000),
                              breaks=seq(0, 40000, 4000),
                              labels=c('0', '4K', '8K', '12K', '16K', '20K',
                                       '24K', '28K', '32K', '36K', '40K'))
p3
```

## Polar coordinates

```{r block14}
t <- seq(0, 360, by=15)
r <- 2
qplot(r, t) + 
coord_polar(theta="y") +
scale_y_continuous(breaks=seq(0, 360, 30)) +
theme(axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank())
```

## Facets

```{r block15}
df <- read_csv("../data/gapminder-data.csv")
p <- ggplot(df, aes(x=gdp_per_capita, y=Electricity_consumption_per_capita)) + geom_point()
p
```

```{r block16, fig.height = 8, fig.width = 4, fig.align="center"}
p + facet_grid(Country ~ .) +
xlab("GDP per capita") +
ylab("Electricity consumption per capita")
```

```{r block17, fig.height = 3, fig.width = 8, fig.align="center"}
p + facet_grid(. ~ Country) +
xlab("GDP per capita") +
ylab("Electricity consumption per capita") +
theme(axis.text.x=element_text(angle=90))
```

```{r block18}
p + facet_wrap(~Country) +
xlab("GDP per capita") +
ylab("Electricity consumption per capita")
```

```{r block19}
ordered_countries <- df %>%
  group_by(Country) %>%
  summarize(mean = round(mean(gdp_per_capita))) %>%
  arrange(desc(mean)) %>%
  mutate(labels = str_c(Country, ": $", mean))
country.labs <- ordered_countries$labels
names(country.labs) <- ordered_countries$Country

df_ordered <- df %>%
  mutate(Country = factor(Country, levels=ordered_countries$Country))

ggplot(df_ordered, aes(x=gdp_per_capita, y=Electricity_consumption_per_capita)) +
  geom_point() +
  facet_wrap(~Country,
             labeller=labeller(Country = country.labs)) +
xlab("GDP per capita") +
ylab("Electricity consumption per capita")
```

## Shapes and colors

```{r block20}
dfs <- subset(df, Country %in% c("Germany", "India", "China", "United States"))
var1 <- "Electricity_consumption_per_capita"
var2 <- "gdp_per_capita"
name1 <- "Electricity/capita"
name2 <- "GDP/capita"
ggplot(df, aes_string(x=var1, y=var2)) +
geom_point(color=2, shape=2) + 
xlim(0, 10000) +
xlab(name1) +
ylab(name2)
```

```{r block21}
ggplot(dfs, aes_string(x=var1, y=var2)) +
geom_point(aes(color=Country, shape=Country)) +
xlim(0, 10000) +
xlab(name1) +
ylab(name2)
```

## Themes

```{r block22}
dfn <- subset(HollywoodMovies,
              Genre %in% c("Action", "Adventure", "Comedy", "Drama",
              "Romantic Comedy") &
              LeadStudio %in% c("Lionsgate ", "Paramount Pictures ",
              "Twentieth Century Fox ", "Universal Pictures ", "Warner Bros. "))
p1 <- ggplot(dfn, aes(x=Genre, y=WorldGross)) 
p2 <- p1 + geom_bar(aes(fill=LeadStudio), stat="Identity", position="dodge")
p2
```

```{r block23}
p3 <- p2 + theme(axis.title.x=element_text(size=15),
                 axis.title.y=element_text(size=15),
                 plot.background=element_rect(fill="gray87"),
                 panel.background=element_rect(fill="beige"),
                 panel.grid.major=element_line(color="Gray", linetype=1))
p3
```

```{r block24, fig.height = 8, fig.width = 8, fig.align="center"}
p4 <- p2 +
  theme_bw() +
  ggtitle("theme_bw()") +
  theme(axis.text.x=element_text(angle=90))
p5 <- p2 +
  theme_classic() +
  ggtitle("theme_classic()") +
  theme(axis.text.x=element_text(angle=90))
p6 <- p2 +
  theme_gray() +
  ggtitle("theme_gray()") +
  theme(axis.text.x=element_text(angle=90))
p7 <- p2 +
  theme_minimal() +
  ggtitle("theme_minimal()") +
  theme(axis.text.x=element_text(angle=90))
ggarrange(p4, p5, p6, p7, ncol=2, nrow=2, common.legend = TRUE, legend="right")
```

```{r block25}
mytheme <- theme(legend.title=element_blank(),
legend.position="bottom",
text = element_text(color="Blue"),
axis.text=element_text(size=12, color="Red"),
axis.title=element_text(size=rel(1.5)))
```

```{r block26, fig.height = 4, fig.width = 12, fig.align="center"}
p2 <- p2 +
  ggtitle("Original Plot")
p8 <- p2 +
  mytheme +
  ggtitle("Changed Plot with my theme")
grid.arrange(p2, p8, ncol=2)
```

```{r block27}
p4 + scale_fill_brewer(palette="Spectral")
```

```{r block28}
p4 + scale_fill_brewer(palette="Pastel1")
```

```{r block29}
p4 + scale_fill_brewer(palette="Oranges")
```
