---
title: "Tidyverse tutorial - Command lines"
author: "Ariane Ducellier"
date: "8/31/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load R packages.

```{r libraries}
library(tidyverse)
library(skimr)
```

# Read data (csv format)

Read csv files with basic R.

```{r read_basic}
df <- read.csv("../data/gapminder-data.csv")
print(class(df))
View(df)
```

Read csv files with tidyverse.

```{r read_csv}
df_t <- read_csv("../data/gapminder-data.csv")
print(class(df_t))
View(df_t)
```

```{r read_csv_sub}
df_t_sub <- read_csv("../data/gapminder-data.csv",
  col_select=c("Country", "Year", "gdp_per_capita"),
  na=c("", "NA"))
View(df_t_sub)
```

# Explore data

Get basic information on the data.

```{r head}
df_t <- read_csv("../data/gapminder-data.csv")
head(df_t, 3)
```

```{r spec}
spec(df_t)
```

```{r glimpse}
glimpse(df_t)
```

```{r summary}
summary(df_t)
```

```{r skim}
skim(df_t)
```

# The pipe operator

```{r iris}
data(iris)
df_iris <- iris %>%
  group_by(Species) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  gather(measure, value, -Species) %>%
  arrange(value)
```

```{r iris_alt}
data(iris)
df_iris_alt <- group_by(iris, Species)
df_iris_alt <- summarize_if(df_iris_alt, is.numeric, mean)
df_iris_alt <- ungroup(df_iris_alt)
df_iris_alt <- gather(df_iris_alt, measure, value, -Species)
df_iris_alt <- arrange(df_iris_alt, value)
```

# Transform data

```{r get_data}
header <- c("age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex", "capital_gain",
  "capital_loss", "hours_per_week", "native_country", "target")
df <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
  col_names=header, trim_ws=TRUE)
```

## Slicing

```{r slice}
df %>% slice_head(n=5)
df %>% slice_tail(n=5)
df %>% slice_min(age, prop=0.10)
df %>% slice_max(age, prop=0.30)
df %>% slice_sample(n=10, replace=TRUE)
```

## Filtering

```{r filter}
df %>% filter(age > 30)
```

## Selecting

```{r select}
df %>% select(marital_status, age)
```

## Unique values

```{r distinct}
df %>% distinct(sex)
```

## Grouping

```{r group}
df %>%
  group_by(workclass) %>%
  summarize(age_avg=mean(age))
```

## Summarizing

```{r summarize}
df %>% group_by(workclass) %>% summarize(n())
df %>% summarize(sum(!is.na(workclass)))
df %>% group_by(workclass) %>% summarize(first(age))
df %>% group_by(workclass) %>% summarize(quantile(age, 0.5))
df %>% group_by(workclass) %>% summarise(sd(capital_gain))
df %>% group_by(workclass) %>% summarise(quantile(age, 0.5))
df %>% select(1, 3, 5, 11, 12, 13) %>% summarise(across(everything(), mean))
```

## Arranging

```{r arrange}
df %>% arrange(native_country)
```