---
title: "Tutorial - Network data"
author: "Ariane Ducellier"
output: pdf_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load R packages.

```{r libraries}
library(igraph)
library(tidyverse)
```

## Simple synthetic graph

```{r}
gd <- graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6))
plot(gd)
```

```{r}
gu <- graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6), directed=FALSE)
plot(gu, vertex.label=NA)
```

## A more complex graph dataset

```{r}
refugeedata <- read_delim("../data/dataset-unhcr-refugees-data-sudan-south-sudan-2016.csv", "," )
```

```{r}
edges <- refugeedata %>%
  drop_na() %>%
  select("ISO_A3_origin",
         "ISO_A3_residence",
         "Total_refugees") %>%
  rename("from"="ISO_A3_origin",
         "to"="ISO_A3_residence",
         "weight"="Total_refugees") %>%
  slice_max(n=15, order_by=weight)
```

```{r}
nodesFrom <- edges %>%
  select("from") %>%
  distinct() %>%
  rename("country"="from")

nodesTo <- edges %>%
  select("to") %>%
  distinct() %>%
  rename("country"="to")

nodes <- bind_rows(nodesFrom, nodesTo) %>% 
  distinct()
```

```{r}
# Generate ID's for all nodes
nodes$ID <- seq.int(nrow(nodes))

# Create the network object
net <- graph_from_data_frame(d=edges, vertices=nodes, directed=TRUE)
```

```{r}
par(mar=c(0, 0, 1, 0))

V(net)$size <- log(strength(net)) + 4
E(net)$width <- log(edges$weight / 350)

edgesSSD <- incident(net, V(net)[name=="SSD"], mode="out")
edgesSDN <- incident(net, V(net)[name=="SDN"], mode="out")
ecol <- rep("gray", ecount(net))
ecol[edgesSSD] <- "orange"
ecol[edgesSDN] <- "gold"

vcol <- rep("gray", vcount(net))
vcol[V(net)$name=="SSD"] <- "orange"
vcol[V(net)$name=="SDN"] <- "gold"

l <- layout_with_lgl(net, maxiter=93)

plot(net, 
     main="Major flows of refugees to and from Sudan and South Sudan in 2016", 
     sub="Source: UNHCR, 2016", 
     layout=l,
     edge.color=ecol,
     edge.curved=.25, 
     edge.arrow.size=log(E(net)$weight)/6, 
     edge.label=E(net)$weight, 
     edge.label.color="black", 
     edge.label.cex=.7, 
     vertex.color=vcol, 
     vertex.label.color="black", 
     vertex.label.cex=log(strength(net))/12)
```
