---
title: "Untitled"
output: pdf_document
date: "2023-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE)
```

```{r}
library(stars)
library(sf)
library(ggplot2)
```

```{r}
harv_boundary <- read_sf("../data/harv/harv_boundary.shp")
harv_dtm <- read_stars("../data/harv/harv_dtmfull.tif")
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm) +
  scale_fill_viridis_c() +
  geom_sf(data=harv_boundary, fill="transparent")
```

```{r}
harv_dtm_cropped <- st_crop(harv_dtm, harv_boundary)
```

```{r}
harv_dtm
harv_dtm_cropped
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm_cropped) +
  scale_fill_viridis_c() +
  geom_sf(data=harv_boundary, fill="transparent")
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm_cropped) +
  scale_fill_viridis_c(na.value="transparent") +
  geom_sf(data=harv_boundary, fill="transparent")
```

```{r}
harv_dtm_masked <- st_crop(harv_dtm, harv_boundary, crop=FALSE)
harv_dtm_masked
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm_masked) +
  scale_fill_viridis_c(na.value="transparent") +
  geom_sf(data=harv_boundary, fill="transparent")
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm_cropped) +
  scale_fill_viridis_c(na.value="transparent") +
  geom_sf(data=harv_boundary, fill="transparent") +
  coord_sf(datum=st_crs(harv_dtm))
```

```{r}
bbox <- st_bbox(c(xmin=731000, ymin=4713000, xmax=732000, ymax=4714000), crs=st_crs(harv_dtm))
```

```{r}
harv_dtm_small <- st_crop(harv_dtm, bbox)
```

```{r}
harv_soils <- read_sf("../data/harv/harv_soils.shp")
harv_soils_small <- st_crop(harv_soils, bbox)
```

```{r}
ggplot() +
  geom_stars(data=harv_dtm_small) +
  scale_fill_viridis_c(na.value="transparent") +
  geom_sf(data=harv_soils_small, fill="transparent")
```


