---
title: "Untitled"
output: pdf_document
date: "2023-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
```

```{r libraries}
library(tidyverse)
library(cowplot)
library(Ecdat)
```

```{r block_44}
df <- read_csv("../data/gapminder-data.csv")
ggplot(df, aes(gdp_per_capita, Electricity_consumption_per_capita)) +   
  geom_point(aes(color=Country)) +
  xlab("GDP per capita") +
  ylab("Electricity consumption per capita")
```

```{r block_45, fig.height=4, fig.width=8}
ggplot(df, aes(gdp_per_capita, Electricity_consumption_per_capita)) +   
  geom_point(aes(color=Country)) +
  xlab("GDP per capita") +
  ylab("Electricity consumption per capita")
```

```{r block_46, fig.asp=0.3, fig.width=8, out.width="50%"}
ggplot(df, aes(gdp_per_capita, Electricity_consumption_per_capita)) +   
  geom_point(aes(color=Country)) +
  xlab("GDP per capita") +
  ylab("Electricity consumption per capita")
```

```{r block_47}
ggsave(filename = "figures/small_memory_size.png", ggplot(mtcars, aes(x=wt, y=mpg)) +
  geom_point(size=2, shape=23) + theme_bw(base_size = 10),
  width = 5, height = 4, dpi = 150, units = "in", device='png')
ggsave(filename = "figures/big_memory_size.png", ggplot(mtcars, aes(x=wt, y=mpg)) +
  geom_point(size=2, shape=23) + theme_bw(base_size = 10),
  width = 5, height = 4, dpi = 300, units = "in", device='png')
ggsave(filename = "figures/big_figure.png", ggplot(mtcars, aes(x=wt, y=mpg)) +
  geom_point(size=2, shape=23) + theme_bw(base_size = 10),
  width = 10, height = 8, dpi = 300, units = "in", device='png')
```

```{r block_48}
us_map <- map_data("state")
us_prod <- Produc[Produc$year==1985,]
us_prod$region <- gsub("_", " ", tolower(us_prod$state))
merged_data <- left_join(us_map, us_prod[, c("region", "gsp")], by="region")
choropleth <- ggplot(merged_data) +
  geom_polygon(aes(x=long, y=lat, group=group, fill=gsp), color="black") +
  theme_void() +
  theme(legend.position="bottom") +
  scale_fill_continuous(guide=guide_colorbar(barheight=unit(2, units="mm"),
                                             barwidth=unit(5, units="cm")))
choropleth
```

```{r block_49}
tristate <- c("new york", "new jersey", "connecticut")
long_lim <- merged_data$long[merged_data$region %in% tristate]
lat_lim <- merged_data$lat[merged_data$region %in% tristate]
outer <- merged_data[!merged_data$region %in% tristate,]

choropleth +
  geom_polygon(data=outer, aes(x=long, y=lat, group=group),
               fill="gray", color="black") +
  coord_fixed(xlim=c(min(long_lim), max(long_lim)),
              ylim=c(min(lat_lim),max(lat_lim)),
              ratio=1.3)
```

```{r projection1}
choropleth + coord_map() +
  ggtitle("Mercator")
```

```{r projection2}
choropleth + coord_map(projection="gilbert") +
  ggtitle("Gilbert")
```

```{r projection3}
choropleth + coord_map(projection="conic", lat0=50) +
  ggtitle("conic - 50")
```

```{r contour}
p <- ggplot(faithfuld, aes(waiting, eruptions, z=density))
```

```{r contour1}
p1 <- p + geom_contour()
p1
```

```{r contour2}
p2 <- p + geom_contour_filled()
p2
```

```{r contour3}
p3 <- p + geom_raster(aes(fill=density)) +
  geom_contour(color="white")
p3
```

