---
title: "Untitled"
output: pdf_document
date: "2023-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
```
```{r read_csv}
df <- read.csv("../data/gapminder-data.csv")
df_t <- read_csv("../data/gapminder-data.csv")
```

```{r read_csv_option}
df_t_sub <- read_csv("../data/gapminder-data.csv",
  col_select=c("Country", "Year", "gdp_per_capita"),
  na=c("", "NA"))
```

```{r head}
head(df_t, 3)
```

```{r tail}
tail(df_t, 3)
```

```{r spec}
spec(df_t)
```

```{r glimpse}
glimpse(df_t)
```

```{r summary}
summary(df_t)
```

```{r skim}
library(skimr)
#skim(df_t) # commented for knitting because of an error with LaTeX
```

```{r read_data}
header <- c("age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex", "capital_gain",
  "capital_loss", "hours_per_week", "native_country", "target")
df <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
  col_names=header, trim_ws=TRUE)
```

```{r slice}
df %>% slice_sample(n=10, replace=TRUE)
```

```{r filter}
df %>% filter(age > 30)
```

```{r select}
df %>% select(marital_status, age)
```

```{r distinct}
df %>% distinct(sex)
```

```{r group}
df %>% group_by(workclass) %>%
  summarize(age_avg=mean(age))
```

```{r summarize}
df %>%
  select(1, 3, 5, 11, 12, 13) %>%
  summarize(across(everything(), mean))
```

```{r arrange}
df %>%
  group_by(education) %>%
  summarize(count=n(),
            avg_net_gain = mean(capital_gain - capital_loss)) %>%
  arrange(desc(avg_net_gain))
```

```{r separate}
df %>% separate(target, into=c("sign", "amount"), sep="\\b")
```

```{r unite}
df %>% unite(sex, race, age, col="description", sep="_", remove=FALSE)
```

```{r mutate}
df %>%
  mutate(total_gain = capital_gain - capital_loss,
         tax = ifelse(total_gain >= 15000,
         total_gain * 0.1,
         0))
```

```{r na}
for (variable in colnames(df)){
  print(
    paste(variable, dim(drop_na(df[df[variable]=="?", variable]))[1])
  )
}
```

```{r replace}
df_replaced <- df %>%
  mutate(workclass=replace(workclass, workclass=="?", NA),
occupation=replace(occupation, occupation=="?", NA),
native_country=replace(native_country, native_country=="?", NA))
```

```{r na_replace}
for (variable in colnames(df_replaced)){
  print(
    paste(variable, dim(drop_na(df_replaced[df_replaced[variable]=="?", variable]))[1])
  )
}
``` 

```{r na_if}
df %>%
  mutate(workclass=na_if(workclass, "?"),
         occupation=na_if(occupation, "?"),
         native_country=na_if(native_country, "?"))
```

```{r recode}
df %>%
  mutate(over_under=recode(target, "<=50K"="under",
                           ">50K"="over")) %>%
  select(target, over_under)
```

```{r cut}
df %>%
  mutate(ave_age = mean(age),
  over_under_age_avg=cut(age,
      c(0, mean(age), max(age)),
      c("Lower than avg", "Above the avg"))) %>%
select(age, ave_age, over_under_age_avg)
```

```{r data}
sales <- data.frame(
  date = c("2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04", "2022-01-05"),
  store_cd= c(1, 2, 3, 4, 5),
  product_cd= c(1, 2, 3, 4, 5),
  qty= c(10, 12, 9, 12, 8), 
  sales= c(30, 60, 45, 24, 32)
)

stores <- data.frame(
  store_cd= c(1, 2, 3, 4, 6),
  address= c("1 main st", "20 side st", "19 square blvd", "101 first st", "1002 retail ave"),
  city= c("Main", "East", "West", "North", "South"), 
  open_hours= c("7-23", "7-23", "9-21", "9-21", "9-21")
  )

products <- data.frame(
  product_cd= c(1, 2, 3, 4, 6),
  description= c("Soft drink", "Frozen snack", "Fruit", "Water", "Fruit 2"),
  unit_price= c(3.0, 5.0, 5.0, 2.0, 4.0), 
  unit_measure= c("each", "each", "kg", "each", "kg")
  )
```

```{r left_join}
sales %>% anti_join(products)
```
