---
title: "Flexdasboard 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)

load("geocodedData.Rdata")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Life expectancy over time

```{r}
mapData %>%
  group_by(continent, year) %>%
  summarise(meanLife = mean(lifeExp)) %>%
  ggplot(aes(x=year, y=meanLife, group=continent, color=continent)) +
  geom_line()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Life expectancy

```{r}
mapData %>%
  filter(year==2007) %>%
  leaflet() %>%
  addTiles() %>%
  setView(lng=0, lat=0, zoom=2) %>%
  addCircles(lng= ~lon,
             lat= ~lat,
             weight=1,
             radius= ~lifeExp * 5000,
             popup= ~paste(country, lifeExp))
```

### GSP per capita

```{r}
mapData %>%
  filter(year==2007) %>%
  leaflet() %>%
  addTiles() %>%
  setView(lng=0, lat=0, zoom=2) %>%
  addCircles(lng= ~lon,
             lat= ~lat,
             weight=1,
             radius= ~log(gdpPercap) * 25000,
             popup= ~paste(country, lifeExp))
```

