---
title: "Ggplot2 tutorial - Command lines Part 3"
author: "Ariane Ducellier"
date: "10/17/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load R packages

```{r libraries}
library(tidyverse)
library(corrplot)
library(gridExtra)
```

# Part 3 - Advanced Geoms and Statistics

## Bubble charts

```{r block30}
df <- read_csv("../data/gapminder-data.csv")
dfs <- subset(df, Country %in% c("Germany", "India", "China", "United States", "Japan"))

ggplot(dfs, aes(x=Year, y=Electricity_consumption_per_capita)) +
  geom_point(aes(size=population, color=Country)) +
  coord_cartesian(xlim=c(1950, 2020)) +
  labs(subtitle="Electricity consumption vs Year", title="Bubble chart") +
  ylab("Electricity consumption") +
  scale_size(breaks=c(0, 1e+8, 0.3e+9, 0.5e+9, 1e+9, 1.5e+9), range=c(1, 5))
```

## Density plots

```{r block31}
df <- read_csv("../data/LoanStats.csv")
df <- df %>% drop_na(grade)
ggplot(df, aes(x=loan_amnt)) +
  geom_density() +
  facet_wrap(~grade) +
  xlab("Loan amount")
```

```{r block32}
df <- read_csv("../data/LoanStats.csv")
df <- df %>% drop_na(grade)
ggplot(df, aes(x=loan_amnt)) +
  geom_density(aes(fill=grade), alpha=1/2) +
  scale_fill_brewer(palette="Dark2") +
  xlab("Loan Amount") +
  theme_light()
```

## Time series

```{r block33}
df_fb <- read_csv("../data/FB.csv")
df_fb$Date <- as.Date(df_fb$Date)
ggplot(df_fb, aes(x=Date, y=Close, group=1)) + 
geom_line(color="black", na.rm=TRUE) +
ggtitle("Daily Closing Stock Prices: Facebook") + 
theme(plot.title = element_text(lineheight=.7, face="bold")) + 
scale_x_date(date_breaks='3 month') +
theme_bw()
```

## Statistical summaries

```{r block34}
df_fb <- read_csv("../data/FB.csv")
df_fb$Date <- as.Date(df_fb$Date)
df_fb$Month <- strftime(df_fb$Date,"%m")
df_fb$Month <- as.numeric(df_fb$Month)
ggplot(df_fb, aes(Month, Close)) + 
geom_point(color="red", alpha=1/2, position=position_jitter(h=0.0, w=0.0)) +
stat_summary(geom="line", fun="mean", color="blue", size=1) +
stat_summary(geom="line", fun="median", color="orange", size=1) +
stat_summary(geom="line", fun="quantile", fun.args=list(probs=.1), linetype=2, color="green", size=1) +
stat_summary(geom="line", fun="quantile", fun.args=list(probs=.9), linetype=2, color="green", size=1) +
scale_x_continuous(breaks=seq(0, 13, 1)) +
ggtitle("Monthly Closing Stock Prices: Facebook") +
theme_classic()
```

## Linear regression

```{r block35}
df <- read_csv("../data/gapminder-data.csv")
dfs <- subset(df, Country %in% c("Germany", "India", "China", "United States", "Japan"))
ggplot(dfs, aes(gdp_per_capita, Electricity_consumption_per_capita)) + geom_point(aes(color=Country)) +
xlim(0, 30000) +
xlab("GDP per capita") +
ylab("Electricity consumption per capita") +
geom_smooth(method=lm, level=0.99)
```

```{r block36}
df <- read_csv("../data/gapminder-data.csv")
dfs <- subset(df, Country %in% c("Germany", "India", "China", "United States", "Japan"))
ggplot(dfs, aes(gdp_per_capita, Electricity_consumption_per_capita, color=Country)) +
geom_point() +
xlab("GDP per capita") +
ylab("Electricity consumption per capita") +
geom_smooth(method=lm)
```

## Setting the horizontal scale

Difference between coord_cartesian and scale_x_continuous

```{r block37}
p <- ggplot(mtcars, aes(disp, wt)) +
  geom_point() +
  geom_smooth()
p1 <- p + scale_x_continuous(limits = c(325, 500)) +
  ggtitle("scale_x_continuous")
p2 <- p + coord_cartesian(xlim = c(325, 500)) +
  ggtitle("coord_cartesian")
p <- p + ggtitle("Original plot")
grid.arrange(p, p1, p2, ncol=2)
```

## Correlations

```{r block38}
df <- read_csv("../data/gapminder-data.csv")
df <- df[, colnames(df)[4:9]]
df <- na.omit(df)
colnames(df) <- c("gdp", "electricity", "mort", "pov", "bmi_m", "bmi_f")
M <- cor(df)
corrplot(M, method="number")
```

```{r block39}
corrplot(M, method="pie")
```

```{r block40}
corrplot(M, method="ellipse")
```

## Maps

```{r block41}
states_map <- map_data("state")
ggplot(states_map, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill="white", colour="black")
```

```{r block42}
ggplot(states_map, aes(x=long, y=lat, group=group)) +    
geom_path() +
  coord_map("mercator")
```

```{r block43}
europe <- map_data("world",
    region=c("Germany", "Spain", "Italy", "France", "UK", "Ireland")) 
ggplot(europe, aes(x=long, y=lat, group=group, fill=region)) +
  geom_polygon(color="black") +
scale_fill_brewer(palette="Set3")
```

Adding data to the map.

```{r block44}
arrests <- as_tibble(USArrests, rownames=NA) %>%
  rownames_to_column("region") %>%
  mutate(region = tolower(region))
states_arrests <- states_map %>% left_join(arrests)
ggplot(states_arrests, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=Murder), color="black") +
  scale_fill_gradient2(low="cornflowerblue", 
                       high="firebrick1", 
                       midpoint = 10)
```
